apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    kind: Sample
    plural: samples
    singular: sample
    shortNames: ["sp"]
  versions:
  - name: v1alpha
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              message:
                type: string
            required:
            - message
    additionalPrinterColumns:
    - name: message
      type: string
      description: message content which want to show
      jsonPath: .spec.message
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
